#!/usr/bin/env python
"""Render docs/RESULTS.md (+ docs/results_tables.md as an appendix) into a single PDF with the figures.

    python scripts/make_report.py                      # -> docs/SynthMRI_results.pdf
    python scripts/make_report.py --no_appendix --out docs/report.pdf

Markdown -> HTML with the ``markdown`` package; HTML -> PDF with headless Chrome (``google-chrome`` /
``chromium``; ``--browser`` to point at another binary). Figures referenced as ``figures/...`` are
embedded as data URIs so the PDF is self-contained. Nothing here touches the run directories.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CSS = """
@page { size: A4; margin: 18mm 16mm; }
body { font-family: "DejaVu Sans", Arial, Helvetica, sans-serif; font-size: 9.5pt; line-height: 1.38; color: #111; max-width: 100%; }
h1 { font-size: 18pt; margin: 0 0 4pt; } h2 { font-size: 13pt; margin: 16pt 0 5pt; border-bottom: 1px solid #ccc; padding-bottom: 2pt; }
h3, h4 { font-size: 10.5pt; margin: 10pt 0 3pt; }
p { margin: 4pt 0 6pt; } ul, ol { margin: 3pt 0 6pt 16pt; padding: 0; } li { margin: 1.5pt 0; }
code { font-family: "DejaVu Sans Mono", Consolas, monospace; font-size: 8.3pt; background: #f3f3f1; padding: 0 2px; border-radius: 2px; }
pre { background: #f3f3f1; padding: 6pt; font-size: 8pt; overflow-x: auto; white-space: pre-wrap; }
table { border-collapse: collapse; font-size: 8pt; margin: 4pt 0 8pt; width: 100%; page-break-inside: avoid; }
th, td { border: 1px solid #d8d8d4; padding: 2.2pt 4pt; text-align: left; vertical-align: top; }
th { background: #f0efeb; } tr:nth-child(even) td { background: #fafaf8; }
img { max-width: 100%; display: block; margin: 6pt auto; page-break-inside: avoid; }
.meta { color: #555; font-size: 8.5pt; margin-bottom: 12pt; }
.appendix { page-break-before: always; }
"""


def embed_images(html: str, base: Path) -> str:
    def repl(m: re.Match) -> str:
        src = m.group(1)
        f = base / src
        if not f.exists() or f.suffix.lower() != ".png":
            return m.group(0)
        data = base64.b64encode(f.read_bytes()).decode()
        return f'src="data:image/png;base64,{data}"'

    return re.sub(r'src="([^"]+)"', repl, html)


def figure_links_to_images(md: str, base: Path) -> str:
    """Turn `figures/x.png` mentions into embedded images (once per figure), keeping the text."""
    seen: set[str] = set()
    out = []
    for line in md.splitlines():
        out.append(line)
        for m in re.finditer(r"`(figures/[^`]+\.png)`", line):
            rel = m.group(1)
            if rel in seen or not (base / rel).exists():
                continue
            seen.add(rel)
            out.append("")
            out.append(f"![{rel}]({rel})")
    return "\n".join(out)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--results", default="docs/RESULTS.md")
    p.add_argument("--tables", default="docs/results_tables.md")
    p.add_argument("--out", default="docs/SynthMRI_results.pdf")
    p.add_argument("--no_appendix", action="store_true")
    p.add_argument("--browser", default=None, help="chrome/chromium binary (default: first of google-chrome, chromium, chromium-browser)")
    p.add_argument("--keep_html", action="store_true", help="also write <out>.html next to the PDF")
    args = p.parse_args()

    import markdown

    results = Path(args.results)
    base = results.parent
    md = results.read_text()
    md = figure_links_to_images(md, base)
    exts = ["tables", "fenced_code", "sane_lists"]
    body = markdown.markdown(md, extensions=exts)
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    meta = f'<p class="meta">SynthMRI results report, generated by scripts/make_report.py from {results.as_posix()} at commit {commit}, {dt.date.today().isoformat()}.</p>'
    html = f"<html><head><meta charset='utf-8'><title>SynthMRI results</title><style>{CSS}</style></head><body>{meta}{body}"
    if not args.no_appendix and Path(args.tables).exists():
        app = markdown.markdown(Path(args.tables).read_text(), extensions=exts)
        html += f'<div class="appendix"><h1>Appendix: auto-generated result tables</h1>{app}</div>'
    html += "</body></html>"
    html = embed_images(html, base)

    browser = args.browser or next((b for b in ("google-chrome", "chromium", "chromium-browser") if shutil.which(b)), None)
    if browser is None:
        sys.exit("no Chrome/Chromium binary found; pass --browser")
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        html_file = Path(td) / "report.html"
        html_file.write_text(html)
        cmd = [browser, "--headless=new", "--disable-gpu", "--no-sandbox", "--no-pdf-header-footer", f"--print-to-pdf={out.resolve()}",
               f"--user-data-dir={td}/profile", html_file.resolve().as_uri()]
        subprocess.run(cmd, check=True, capture_output=True, timeout=180)
        if args.keep_html:
            shutil.copy(html_file, out.with_suffix(".html"))
    print(f"wrote {out} ({out.stat().st_size / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
